# Generated by Django 2.2.24 on 2023-01-14 07:28

from django.db import migrations

import phonenumbers


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        phone_number = flat.owners_phonenumber
        normalized_phonenumber = phonenumbers.parse(phone_number, 'RU')
        if phonenumbers.is_valid_number(normalized_phonenumber):
            flat.owner_pure_phone = normalized_phonenumber
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230114_1006'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber),
    ]
