# Generated by Django 2.2.24 on 2023-01-14 08:44

from django.db import migrations


def assign_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner_flats = Flat.objects.filter(owner=owner.owner)
        owner.flats_in_property.set(owner_flats)



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230114_1216'),
    ]

    operations = [
        migrations.RunPython(assign_owner),
    ]
